# Generated by Django 4.2.7 on 2023-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='Имя формы')),
                ('date', models.CharField(blank=True, max_length=256, null=True, verbose_name='Дата')),
                ('phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Почта')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='Текст')),
            ],
        ),
    ]
